### ISSUE TITLE
Power on issue

### ISSUE THREAD

**Issue by cwilliams85** [craic/pi_power#1]
Here's the email, contribute away public!

So, I was attempting to use your script and I have two issues.

First, the mcp3008 very intermittently gets voltage data. Not entirely sure why, but I changed your script to not shutdown on that and just poll every second. About 1 in 50 polls gets data. I'm prone to think it's my connections, or a funky chip, but maybe you can't provide insight.

Second, the power switch. I'm going from a powerboost basic, because I have a rpi3, not sure if that matters. I can't get the thing to boot, it just power cycles over and over again. I've tried with and without the power off circuit, with and without capacitors. That one is wired as battery --> switch --> a split between gpio 14 and en pin and then en to ground with the proper resistors and diodes in place. As far as I can tell there's nothing in the script that is needed to power it on with this method, but maybe I'm wrong and that's my issue. I don't think there is enough time for the script to be run before the pi switches off though.

It should probably be noted that first installed back in December, but have since ran the update, upgrade, and dist-upgrade scripts. Currently, I'm not home so I can't verify what versions of Linux and the raspberry pi 3 I have.

**Comment by craic** [comment]
Not sure what to say about the MCP3008 Analog Digital Converter - the best approach is to wire up a circuit using it aside form the Pi Power circuit/code and verify that it does/does not work correctly... interference in breadboard circuits can be a problem - keep your leads short, keep it away from monitors or any other potential source of interference


As regards the immediate shutdown, this might be a result of changes in the latest raspi-config

You are following the Pi3 version of the description, right ?

Unfortunately that tool does not seem to list a version number... it has changed twice in recent history (over the last 6 months)

So make sure you have the latest version of the Command Line Tool (not the GUI version)
 'sudo raspi-config' -> #8 Update ...
In the latest version go #5 Interfacing Options -> P6 Serial ->  and then...
Would you like a login shell to be accessible over serial?   NO
Would you like the serial port hardware to be enabled? YES
-> OK -> Finish ... then reboot and see if that solves the issue

The prior version only had one option and I suspect this might be part of the problem.

I'll try and update the software on my pi_power test circuit and then test it out myself - but unfortunately it will be a few days before I can get to this...

Let me know how it works...

**Comment by cwilliams85** [comment]
No luck on this end so far. I can't wait for it to be something stupid (always is).

I did the update, and resetup the interfacing options, still no luck. Also, yes, its wired as per your diagram for the pi3.

**Comment by cwilliams85** [comment]
I was messing around with various setups and managed to boot it with a usb cable (although not even close to a way that should be reproduced...)

Anyways, during the boot up process my eye caught a line "[FAILED] Failed to start Configure Bluetooth Modems connected by UART." Confusing because I don't have anything bluetooth connected, think that might be part of my aches?

I also noticed that the voltage drops from the battery voltage to the just after the switch. In my current case 3.87v to around 1.52v. When I disconnect the resistor going to ground it goes back to the proper voltage. Not entirely sure if this is intended or not.

**Comment by craic** [comment]
On Sun, Mar 5, 2017 at 5:02 PM, cwilliams85 <notifications@github.com>
wrote:

> I was messing around with various setups and managed to boot it with a usb
> cable (although not even close to a way that should be reproduced...)
>
Hmm... does that imply that you were NOT powering it with a USB cable
before?

You weren't trying to wire directly into the Pi 5V pin, were you?

That might cause various issues as I THINK that bypasses power control
circuitry on the Pi board...


> Anyways, during the boot up process my eye caught a line "[FAILED] Failed
> to start Configure Bluetooth Modems connected by UART." Confusing because I
> don't have anything bluetooth connected, think that might be part of my
> aches?
>

I don't think so...

**Comment by cwilliams85** [comment]
Interesting. Unfortunately my setup kind of requires it to be through the gpio pins. I'm mashing my RetroPie project into a Wii u gamepad. I might be able to squeeze a USB cable in there, but I'm fairly sure the original project I'm basing my on went through the gpio pins (and I do know the risk of blowing up the pi from doing this) but I know he used your script and wiring to power the thing. 

Here's a link to the project, maybe you see something I don't with the limited amount of information and pictures provided. http://sudomod.com/forum/viewtopic.php?f=13&t=1607

I'm going to reinstall RetroPie tonight and see if that makes a difference. Maybe something else I have is disabling this from working. 

And for the sake of completing this, I'll power it through the USB to see if there is an impact.

**Comment by craic** [comment]
OK - I'll dig into the Pi schematics and see what, if anything you are
bypassing

**Comment by cwilliams85** [comment]
I believe it's just the poly fuse. Still, not sure of the culprit, but that voltage drop seems suspect.

**Comment by cwilliams85** [comment]
Partial success, granted only half is wired in. I turned off the second option "serial port hardware" and it'll boot until I stop pressing the momentary switch.

**Comment by cwilliams85** [comment]
On further examination, having either configuration on the serial option nets the same result. In addition, using a capacitor or not across the en/ground resistor has the same result.

 I've also stripped a USB cable, so we can rule that out. Also, I can rule out anything I might have changed software wise. I reflashed my SD card to RetroPie 4.1 and then updated it. I'm probably going to reinstall one more time and not update just for the sake of it.

**Comment by cwilliams85** [comment]
Well, I reinstalled on 4.1 RetroPie and left the raspi-config tool, disto update, and upgrade alone. Power up works now. Haven't wired the power down portion back in, but I'm hopeful.

Just praying the upgrade doesn't make me miss out on some functionality I want...

**Comment by cwilliams85** [comment]
As for the battery monitor, I had to use gpio pins 5,6,19,26, gnd. So that works now. I guess we can close this with the solution of "don't upgrade anything and hope for the best.
